name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Java JDK
        uses: actions/setup-java@v6.0.0
        with:
          distribution: microsoft
          java-version: 25

      - name: Gradle Build Action
        uses: gradle/actions/setup-gradle@v6.3.0

      # ubuntu only
      - name: Fix Permission Denied
        run: chmod 777 ./gradlew
      
      - name: Build plugin
        run: ./gradlew buildPlugin
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: mybatisuite
          path: build/distributions/
